//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication28.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int userid { get; set; }
        public string username { get; set; }
        public Nullable<int> age { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public string gender { get; set; }
        public Nullable<int> contact { get; set; }
    }
}
