//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication28.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class club
    {
        public int ClubNo { get; set; }
        public string ClubName { get; set; }
        public string Address { get; set; }
        public Nullable<int> Pincode { get; set; }
        public Nullable<long> Contact { get; set; }
    }
}
