//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication28.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembershipPlan
    {
        public int Plan_Id { get; set; }
        public string Plan_Name { get; set; }
        public string Plan_Duration { get; set; }
        public Nullable<int> Plan_Fees { get; set; }
        public string Plan_Description { get; set; }
    }
}
